version: "2"

services:
  clips:
    image: ghcr.io/brilliant-monkey/frigate-clips:latest
    environment:
      - FRIGATE_CLIPS_CONFIG_PATH=/app/config.yml
      - PORT=8777
    ports:
      - 8080:8777
    volumes:
      - ./secret.docker.yml:/app/config.yml:ro
      - ./clips/:/app/clips:rw
    depends_on:
      - frigate-kafka-relay
      - kafka
  frigate-kafka-relay:
    image: ghcr.io/brilliant-monkey/frigate-kafka-relay:latest
    environment:
      - FRIGATE_KAFKA_RELAY_CONFIG_PATH=config.yml
      - PORT=8082
    ports:
      - 8082:8082
    volumes:
      - ./relay.secret.docker.yml:/app/config.yml:ro
    depends_on:
      - kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
