apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-clips-storage
  labels:
    app: frigate-clips
    platform: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi